services:
  backend:
    build:
      dockerfile: ./backend/Dockerfile
      context: ./
      args:
        - ENVIRONMENT=local
    ports:
      - "8000:8000"
      - "2222:2222"
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    volumes:
      - ./backend:/app/backend
    networks:
      - sum-calculator  
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
      context: ./
      target: build
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    networks:
      - sum-calculator

networks:
  sum-calculator:
    driver: bridge