name: Azure Static Web App CI/CD

on:
  push:
    branches:
      - main  # Update with your branch name
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main  # Update with your branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.8.1'

      - name: Install frontend dependencies
        run: yarn --cwd frontend install

      - name: Build frontend
        run: yarn --cwd frontend build

      - name: Archive production build
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: frontend/build

      - name: Deploy to Azure Static Web Apps
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "frontend"
          output_location: "frontend/build"
