name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build and Push Docker Image
      run: |
        docker build -t brenno/app:latest ./backend
        docker tag brenno/app ${{ secrets.ACR_SERVER }}/${{ secrets.IMAGE_NAME }}
        docker login ${{ secrets.ACR_SERVER }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
        docker push ${{ secrets.ACR_SERVER }}/${{ secrets.IMAGE_NAME }}
