on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 58 8 * * *
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.8.1'

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install

      - name: Run Prettier
        working-directory: ./frontend
        run: yarn prettier

      - name: Run Tests
        working-directory: ./frontend
        run: yarn test --passWithNoTests
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.8.1'

      - name: Install dependencies
        working-directory: ./backend
        run: pipenv install | pipenv shell | npm install

      - name: Run Server
        working-directory: ./backend
        run: uvicorn main:app --reload &

      - name: Run tests
        working-directory: ./backend
        run: newman run postman/Intensivao-Devops.postman_collection.json
