name: pr-pipeline

on: pull_request

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci

  backend-frontend:
    runs-on: ubuntu-20.04
    container:
      image: docker:latest
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run containers
        run: docker-compose up --build -d

      - name: Run frontend tests
        run: docker-compose exec frontend yarn test --passWithNoTests

      - name: Run frontend linter
        run: docker-compose exec frontend yarn prettier

      - name: Run backend tests
        run: docker-compose exec backend newman run postman/Intensivao-Devops.postman_collection.json

      - name: Stop containers
        run: docker-compose down
