name: PR Pipeline

on: pull_request

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
  backend:
    name: backend
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Newman
        run: npm install -g newman

      - name: Run backend tests
        working-directory: ./backend
        run: |
          docker-compose -f ../docker-compose-ci.yml up --build -d
          sleep 5
          newman run postman/Intensivao-Devops.postman_collection.json
  frontend:
    name: frontend
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.8.1'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install

      - name: Run frontend linter
        working-directory: ./frontend
        run: yarn prettier

      - name: Run frontend tests
        working-directory: ./frontend
        run: yarn test --passWithNoTests