name: Build and deploy container app to Azure Web App - sum-calculator-web-app

on:
  workflow_run:
    workflows: ["Build Artifacts"]
    types:
      - completed

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Get run_number
      uses: actions/download-artifact@v2
      with:
        name: run_number
        path: .
          
    - name: Generate Backend Semantic Version
      id: backend_version
      run: echo "::set-output name=version::1.0.$(cat run_number.txt)"
        
    - name: Deploy to Azure Web App
      
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sum-calculator-web-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_008d67032fca4db98179f44c50b0bead }}
        images: 'inspiradevops.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_792aa0849f8d49e0a3ae051198c4fdc4 }}/brenno-app:${{ steps.backend_version.outputs.version }}"'
  
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Get run_number
        uses: actions/download-artifact@v2
        with:
          name: run_number
          path: .
        
      - name: Generate Frontend Semantic Version
        id: frontend_version
        run: echo "::set-output name=version::1.0.$(cat run_number.txt)"

      - name: Download frontend artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: frontend_build
          version: ${{ steps.frontend_version.outputs.version }}

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_FOREST_0E6CD570F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend_build"
          output_location: "frontend/build"
          skip_app_build: true
